# Forcer S3A comme filesystem par défaut
# et neutraliser HDFS
spark.hadoop.fs.defaultFS                         s3a://dbt-bucket/iceberg_warehouse

# S3 / MinIO
spark.hadoop.fs.s3a.impl                          org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider      org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.access.key                    minioadmin
spark.hadoop.fs.s3a.secret.key                    minioadmin
spark.hadoop.fs.s3a.region                        us-east-1
spark.hadoop.fs.s3a.path.style.access             true
spark.hadoop.fs.s3a.endpoint                      http://192.168.70.2:9000

# Warehouse Iceberg sur S3
spark.sql.warehouse.dir                           s3a://dbt-bucket/iceberg_warehouse

# Catalog REST Gravitino
spark.sql.extensions                              org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.defaultCatalog                          rest_catalog
spark.sql.catalog.rest_catalog                    org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.rest_catalog.type               rest
spark.sql.catalog.rest_catalog.uri                http://192.168.70.2:8181/iceberg/
spark.sql.catalog.rest_catalog.s3.endpoint        http://192.168.70.2:9000
spark.sql.catalog.rest_catalog.s3.path-style-access       true
spark.sql.catalog.rest_catalog.s3.access-key-id           minioadmin
spark.sql.catalog.rest_catalog.s3.secret-access-key       minioadmin
spark.sql.catalog.rest_catalog.s3.region                  us-east-1

#EXtra Path
spark.driver.extraClassPath             /home/jovyan/.ivy2/jars/*
spark.executor.extraClassPath             /home/jovyan/.ivy2/jars/*

spark.jars                              /home/jovyan/.ivy2/jars/*

# Time out
# Timeouts réseau
spark.network.timeout                   600s
spark.files.io.connectionTimeout        600s
spark.rpc.askTimeout                    600s
spark.rpc.lookupTimeout                 600s
spark.sql.broadcastTimeout              600

# Heartbeat — évite que le driver soit considéré mort
spark.executor.heartbeatInterval        30s
spark.network.timeoutInterval           120s

# S3A timeouts
spark.hadoop.fs.s3a.connection.timeout  300000
spark.hadoop.fs.s3a.socket.timeout      300000
spark.hadoop.fs.s3a.attempts.maximum   10

