# .github/workflows/cd.yml

name: cd dbt

on:
  push:
    branches: [ "main" ]

    paths:
      - "dbt-project/my_project/models/**"
      - "dbt-project/my_project/macros/**"
      - "dbt-project/my_project/seeds/**"
      - "dbt-project/my_project/tests/**"
      - "dbt-project/my_project/snapshots/**"
      - "dbt-project/my_project/packages.yml"
      - ".github/workflows/cd.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

env:
  MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}     


jobs:

  #-------deployment--------

  deployment:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./dbt-project/my_project

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: create dbt container
        run: |
          docker rm -f dbt-cont 2>/dev/null || true

          docker run -d --name dbt-cont \
                -v $(pwd)/:/workspace \
                dbt-pyspark-user:3.5.3 tail -f /dev/null
            
      
      - name: dbt deps
        run: docker exec dbt-cont dbt deps

      - name: download prod artifacts manifest.json from minio
        run: |
          docker run --rm \
                 --entrypoint=/bin/sh \
                -w /workspace \
                -v $(pwd):/workspace \
                minio/mc -c " 
                  mc alias set my_minio http://192.168.70.2:9000 '$MINIO_ACCESS_KEY' '$MINIO_SECRET_KEY'  &&

                  mc cp my_minio/dbt-bucket/dbt-artifacts/manifest.json \
                      ./artifacts-prod/manifest.json  
                "


      - name: dbt build
        run: |
          docker exec dbt-cont dbt build \
            --target prod \
            --target-path ./target-prod \
            --select state:modified+ \
            --defer \
            --state ./artifacts-prod

      - name: upload prod artifacts manifest.json to minio
        run: |
          docker run --rm \
                --entrypoint=/bin/sh \
                -w /workspace \
                -v $(pwd):/workspace \
                minio/mc -c " 
                    mc alias set my_minio http://192.168.70.2:9000 '$MINIO_ACCESS_KEY' '$MINIO_SECRET_KEY'  &&

                    mc cp ./target-prod/manifest.json \
                                  my_minio/dbt-bucket/dbt-artifacts/manifest.json
                                    
                "

      - name: cleanup
        if: always()
        run: |
         docker rm -f dbt-cont || true